import { Card, CardContent } from '../components/common/Card';
import { StatusBadge } from '../components/widgets/StatusBadge';
import { Badge } from '../components/common/Badge';
import { Lightbulb } from 'lucide-react';

const RECS = [
  { id: 'r1', customer: 'c_01000', type: 'Retention Offer', priority: 'high', confidence: 0.92, reason: 'CLV > $500, churn prob 72%', impact: '$542 CLV recovery', cost: 50, policy: 'APPROVED', status: 'Completed', generated_by: 'policy_engine' },
  { id: 'r2', customer: 'c_01023', type: 'Win-back Campaign', priority: 'medium', confidence: 0.78, reason: 'Inactive 120 days', impact: '$180 CLV recovery', cost: 25, policy: 'PENDING', status: 'PendingApproval', generated_by: 'llm_reasoning' },
  { id: 'r3', customer: 'c_02150', type: 'Premium Upgrade', priority: 'high', confidence: 0.91, reason: 'Top 5% by CLV', impact: '$420 annual increase', cost: 0, policy: 'APPROVED', status: 'Executing', generated_by: 'policy_engine' },
  { id: 'r4', customer: 'c_03200', type: 'Loyalty Reward', priority: 'low', confidence: 0.65, reason: 'Moderate engagement', impact: '$90 retention', cost: 15, policy: 'APPROVED', status: 'Completed', generated_by: 'llm_reasoning' },
];

export default function RecommendationCenter() {
  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div><h1 className="text-2xl font-bold">Recommendation Center</h1><p className="text-sm text-muted-foreground mt-1">{RECS.length} recommendations</p></div>
        <Lightbulb className="w-5 h-5 text-primary" />
      </div>
      <Card>
        <CardContent className="p-0">
          <table className="w-full text-sm">
            <thead><tr className="border-b border-border">
              <th className="text-left p-4 font-medium text-muted-foreground">Customer</th>
              <th className="text-left p-4 font-medium text-muted-foreground">Type</th>
              <th className="text-left p-4 font-medium text-muted-foreground">Confidence</th>
              <th className="text-left p-4 font-medium text-muted-foreground">Impact</th>
              <th className="text-left p-4 font-medium text-muted-foreground">Cost</th>
              <th className="text-left p-4 font-medium text-muted-foreground">Generated By</th>
              <th className="text-left p-4 font-medium text-muted-foreground">Status</th>
            </tr></thead>
            <tbody>
              {RECS.map((r) => (
                <tr key={r.id} className="border-b border-border/50 hover:bg-muted/30 transition-colors">
                  <td className="p-4 font-mono text-xs">{r.customer}</td>
                  <td className="p-4">{r.type}</td>
                  <td className="p-4"><Badge variant={r.confidence > 0.8 ? 'success' : 'warning'}>{(r.confidence * 100).toFixed(0)}%</Badge></td>
                  <td className="p-4 text-xs">{r.impact}</td>
                  <td className="p-4">${r.cost}</td>
                  <td className="p-4"><span className="text-xs font-mono bg-muted/50 px-1.5 py-0.5 rounded">{r.generated_by}</span></td>
                  <td className="p-4"><StatusBadge status={r.status} /></td>
                </tr>
              ))}
            </tbody>
          </table>
        </CardContent>
      </Card>
    </div>
  );
}
