"""
Enterprise AI Customer Intelligence Platform — Agent State.

Defines the LangGraph state dictionary passed between nodes.
"""

from typing import Annotated, Any, Dict, List, Optional, TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    """The state maintained throughout the LangGraph execution."""
    # Conversation history. add_messages appends new messages automatically.
    messages: Annotated[List[BaseMessage], add_messages]
    
    # Metadata and context
    customer_id: Optional[str]
    conversation_id: str
    
    # Execution plan generated by the Planner node
    plan: str
    
    # Raw JSON string output from tool execution
    tool_outputs: str
    
    # Final recommendation generated by the rules engine
    recommendation: str
    
    # List of tool names that were actually invoked
    tools_used: List[str]
